title: Точки — Анализ
description: >-
  Совершенствование теории игры точки.
# url: ""
email: demindf@gmail.com
twitter_username: fezon000
github_username:  demin-dmitriy

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed
